spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  liquibase:
    url: jdbc:h2:file:./mydb.db
    user: sa
    password: ''
  r2dbc:
    url: r2dbc:h2:file:///./mydb.db
    username: sa
    password: ''

logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG